name: houlala
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  auto_size_text: ^3.0.0
  connectivity_plus: ^6.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_markdown: ^0.7.1
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.1
  intl: ^0.19.0
  path_provider: ^2.1.2
  provider: ^6.1.1
  sizer: ^2.0.15
  url_launcher: ^6.2.4
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  heroicons: ^0.10.0
  google_fonts: ^6.1.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  collection: ^1.18.0
  webview_flutter: ^4.7.0
  webview_flutter_wkwebview: ^3.13.0
  toastification: ^2.0.0
  pocketbase: ^0.18.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.7.1
flutter_icons:
  android: true
  ios: true
  image_path: "images/houlala.png"
  adaptive_icon_background: "#e19a30"
  adaptive_icon_foreground: "images/houlala_foreground.png"
flutter:
  uses-material-design: true
  assets:
    - images/houlala.png
    - texts/security.md
    - texts/condition.md
    - texts/about.html
    - images/whatsapp.png
    - images/youtube.png
    - images/facebook.png
    - images/instagram.png
    - images/wifi-x.png
    - images/comment.png
    - images/no-notification.png
    - images/cart.png
    - images/house.png
    - images/linkedin.png
    - images/houlala1.png
    - images/category.png
    - images/big_category.png
    - images/hand-shake.png
    - images/categories.png
    - images/sound-off.png
    - images/stock.png
    - images/no-shopping-cart.png
    - images/customer-service.png
    - images/shop.png
    - images/no-talk.png
    - images/heart.png
    - images/about.png
    - images/contact-mail.png
    - images/log-out.png
    - images/privacy-policy.png
    - images/shopping-bag.png
    - images/sign-in.png
    - images/terms-and-conditions.png
    - images/user.png
    - ca/lets-encrypt-r3.pem
    - texts/term.html
    - texts/conditions.html
    - images/notification.png
    - images/shopping.png
    - images/store.png
    - images/house_fill.png
    - images/categorie_fill.png
    - images/cart_fill.png
    - images/bell_fill.png
    - images/user_fill.png
    - .env


