name: houlala
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1


environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  auto_size_text: ^3.0.0
  connectivity_plus: ^3.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_markdown: ^0.6.14
  flutter_secure_storage: ^8.0.0
  font_awesome_flutter: ^10.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  intl: ^0.18.0
  launch_review: ^3.0.1
  path_provider: ^2.0.14
  provider: ^6.0.5
  responsive_builder: ^0.6.4
  sizer: ^2.0.15
  url_launcher: ^6.1.10
  webview_flutter_plus: ^0.3.0+2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  flutter_launcher_icons: ^0.9.3


flutter_icons:
  android: true
  ios: true
  image_path: "images/houlala.png"
  adaptive_icon_background: "#e19a30"
  adaptive_icon_foreground: "images/houlala_foreground.png"

flutter:


  uses-material-design: true
  fonts:
     - family: Poppins
       fonts:
         - asset: fonts/Poppins-Regular.ttf
     - family: PoppinsBold
       fonts:
         - asset: fonts/Poppins-Bold.ttf

  assets:
    - images/houlala.png
    - texts/security.md
    - texts/condition.md
    - texts/about.html
    - images/whatsapp.png
    - images/youtube.png
    - images/facebook.png
    - images/instagram.png
    - images/wifi-x.png
    - images/comment.png
    - images/no-notification.png
    - images/cart.png
    - images/house.png
    - images/linkedin.png
    - images/houlala1.png
    - images/category.png
    - images/big_category.png
    - images/hand-shake.png
    - images/categories.png
    - images/sound-off.png
    - images/stock.png
    - images/no-shopping-cart.png
    - images/customer-service.png
    - images/shop.png
    - images/no-talk.png
    - images/heart.png
    - images/about.png
    - images/contact-mail.png
    - images/log-out.png
    - images/privacy-policy.png
    - images/shopping-bag.png
    - images/sign-in.png
    - images/terms-and-conditions.png
    - images/user.png
    - ca/lets-encrypt-r3.pem
    - texts/term.html
    - texts/conditions.html
    - images/notification.png
    - images/shopping.png
    - images/store.png
    - .env


